version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: idrd
      MYSQL_DATABASE: idrd
      MYSQL_USER: idrd
      MYSQL_PASSWORD: idrd
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"